export const Resources = [
    ['bg_day', './res/bg_day.png'],
    ['bg_night', './res/bg_night.png'],
    ['land', './res/land.png'],
    ['pipe_up','./res/pipe_up.png'],
    ['pipe_down','./res/pipe_down.png'],
    ['pipe2_up','./res/pipe2_up.png'],
    ['pipe2_down','./res/pipe2_down.png'],
    ['bird0_0', './res/bird0_0.png'],
    ['bird0_1', './res/bird0_1.png'],
    ['bird0_2', './res/bird0_2.png'],
    ['bird1_0', './res/bird1_0.png'],
    ['bird1_1', './res/bird1_1.png'],
    ['bird1_2', './res/bird1_2.png'],
    ['bird2_0', './res/bird2_0.png'],
    ['bird2_1', './res/bird2_1.png'],
    ['bird2_2', './res/bird2_2.png'],
    ['gameOver', './res/text_game_over.png'],
    ['button_resume', './res/button_resume.png'],
    ['button_pause', './res/button_pause.png'],
    ['score0', './res/number_score_00.png'],
    ['score1', './res/number_score_01.png'],
    ['score2', './res/number_score_02.png'],
    ['score3', './res/number_score_03.png'],
    ['score4', './res/number_score_04.png'],
    ['score5', './res/number_score_05.png'],
    ['score6', './res/number_score_06.png'],
    ['score7', './res/number_score_07.png'],
    ['score8', './res/number_score_08.png'],
    ['score9', './res/number_score_09.png']
]